export interface StickerPlan {
  id: string;
  title: string;
  emotion: string;
  posePrompt: string;
  actionPrompt: string;
  caption: string;
}

/** Authored scenes, shared by the free illustration library and AI requests. */
export const STICKER_PLANS: readonly StickerPlan[] = [
  {
    id: 'hello',
    title: '반가워!',
    emotion: '다정한 인사',
    posePrompt: '서서 한 손을 높이 들고 손바닥을 보여 주며 인사하는 자세',
    actionPrompt: '한쪽 팔꿈치와 손목으로 손 인사하고 눈을 한 번 깜빡여요.',
    caption: '안녕!',
  },
  {
    id: 'love',
    title: '마음을 줄게',
    emotion: '사랑',
    posePrompt: '두 팔로 커다란 분홍 하트를 꼭 끌어안고 앉은 자세',
    actionPrompt: '하트를 안은 두 손을 살짝 조이고 눈을 웃는 모양으로 감았다 떠요.',
    caption: '좋아해',
  },
  {
    id: 'sleepy',
    title: '꾸벅꾸벅',
    emotion: '졸음',
    posePrompt: '옆으로 누워 구름 베개에 볼을 기대고 한 손을 베고 있는 자세',
    actionPrompt: '졸린 눈꺼풀이 천천히 닫히고 작은 입이 하품해요.',
    caption: '졸려…',
  },
  {
    id: 'thanks',
    title: '고마워요',
    emotion: '감사',
    posePrompt: '작은 꽃다발을 두 손으로 모아 들고 고개를 숙인 자세',
    actionPrompt: '꽃을 든 손을 가슴 가까이 당기고 웃는 눈을 부드럽게 깜빡여요.',
    caption: '고마워요',
  },
  {
    id: 'cheer',
    title: '할 수 있어!',
    emotion: '응원',
    posePrompt: '두 주먹을 머리 옆으로 올리고 두 발을 벌려 힘차게 응원하는 자세',
    actionPrompt: '양팔의 주먹을 번갈아 작게 들어 올리며 활짝 웃어요.',
    caption: '파이팅!',
  },
  {
    id: 'sorry',
    title: '미안해요',
    emotion: '미안함',
    posePrompt: '무릎을 모으고 손을 앞에 공손히 모은 작고 조심스러운 자세',
    actionPrompt: '모은 손가락을 꼼지락거리고 눈을 미안한 모양으로 감았다 떠요.',
    caption: '미안해',
  },
  {
    id: 'laugh',
    title: '웃음 폭발',
    emotion: '기쁨',
    posePrompt: '한 손으로 배를 잡고 다른 손으로 입을 가린 채 옆으로 기울어 웃는 자세',
    actionPrompt: '입을 크게 웃었다 다물고 배 위의 손가락이 조금 움직여요.',
    caption: '하하하!',
  },
  {
    id: 'cry',
    title: '눈물이 주룩',
    emotion: '슬픔',
    posePrompt: '바닥에 주저앉아 한 손으로 눈물을 닦고 다른 손에 손수건을 든 자세',
    actionPrompt: '손수건으로 볼을 톡톡 닦고 눈꺼풀을 꼭 감았다 떠요.',
    caption: '엉엉',
  },
  {
    id: 'surprise',
    title: '깜짝이야!',
    emotion: '놀람',
    posePrompt: '두 손바닥을 양옆으로 활짝 펴고 눈과 입을 동그랗게 뜬 자세',
    actionPrompt: '벌린 손가락이 움찔하고 동그란 입이 작아졌다 다시 커져요.',
    caption: '헉!',
  },
  {
    id: 'angry',
    title: '흥, 삐졌어',
    emotion: '화남',
    posePrompt: '두 손을 허리에 대고 볼을 부풀리며 발을 넓게 디딘 자세',
    actionPrompt: '눈썹을 찌푸리고 한 손을 허리에서 떼었다 다시 짚어요.',
    caption: '흥!',
  },
  {
    id: 'okay',
    title: '좋아요, 오케이',
    emotion: '동의',
    posePrompt: '한 손을 얼굴 옆에 둥글게 들고 반대 손을 허리에 둔 자신 있는 자세',
    actionPrompt: '얼굴 옆 손목을 가볍게 접었다 펴며 한쪽 눈을 윙크해요.',
    caption: '오케이',
  },
  {
    id: 'no',
    title: '안 돼요',
    emotion: '단호함',
    posePrompt: '두 팔을 가슴 앞에서 X자로 교차하고 입을 단단히 다문 자세',
    actionPrompt: 'X자로 모은 손목을 살짝 교차했다 원래 자리로 돌려요.',
    caption: '안 돼!',
  },
  {
    id: 'yes',
    title: '알겠어요',
    emotion: '수긍',
    posePrompt: '두 손바닥을 가슴 앞에서 위로 펴고 반듯하게 서 있는 자세',
    actionPrompt: '한쪽 손바닥을 살짝 올리고 두 눈을 짧게 감았다 떠요.',
    caption: '알겠어',
  },
  {
    id: 'hungry',
    title: '배고파요',
    emotion: '배고픔',
    posePrompt: '빈 밥그릇과 숟가락을 각각 들고 입맛을 다시며 앉은 자세',
    actionPrompt: '숟가락을 든 손을 살짝 움직이고 입이 맛있는 것을 상상하듯 오물거려요.',
    caption: '밥 먹자',
  },
  {
    id: 'yummy',
    title: '냠냠 맛있어',
    emotion: '만족',
    posePrompt: '커다란 간식을 한 손에 들고 다른 손을 볼에 대며 맛있게 먹는 자세',
    actionPrompt: '간식을 입 가까이 가져왔다 내리고 입과 눈으로 맛있게 씹는 표정을 지어요.',
    caption: '냠냠',
  },
  {
    id: 'coffee',
    title: '잠깐 쉬어요',
    emotion: '여유',
    posePrompt: '따뜻한 머그잔을 두 손에 감싸 쥐고 편하게 앉은 자세',
    actionPrompt: '머그잔 위로 손가락을 감싸고 눈을 느긋하게 감았다 떠요.',
    caption: '커피 한 잔',
  },
  {
    id: 'busy',
    title: '열심히 작업 중',
    emotion: '집중',
    posePrompt: '노트북 앞에 앉아 두 손을 키보드 위에 올리고 집중하는 자세',
    actionPrompt: '두 손가락이 번갈아 키보드를 두드리고 눈을 한 번 깜빡여요.',
    caption: '작업 중',
  },
  {
    id: 'hurry',
    title: '지금 가는 중',
    emotion: '서두름',
    posePrompt: '한 무릎을 높이 들고 반대 다리를 뒤로 뻗으며 달리는 자세',
    actionPrompt: '몸통은 고정한 채 팔꿈치와 손목을 앞뒤로 작게 움직여 달리는 인사를 해요.',
    caption: '금방 가!',
  },
  {
    id: 'waiting',
    title: '기다릴게요',
    emotion: '기다림',
    posePrompt: '한 손으로 턱을 괴고 다른 손목의 작은 시계를 바라보며 앉은 자세',
    actionPrompt: '턱 아래 손가락이 살짝 움직이고 눈길을 시계 쪽으로 깜빡여요.',
    caption: '기다릴게',
  },
  {
    id: 'tired',
    title: '방전됐어요',
    emotion: '피곤함',
    posePrompt: '다리를 앞으로 쭉 뻗고 어깨와 양팔을 축 늘어뜨린 자세',
    actionPrompt: '처진 눈을 느리게 감고 작은 입으로 길게 한숨 쉬어요.',
    caption: '충전 필요',
  },
  {
    id: 'confused',
    title: '음, 모르겠어',
    emotion: '궁금함',
    posePrompt: '한 손은 머리 옆에, 다른 손바닥은 위로 펴고 갸웃한 자세',
    actionPrompt: '머리 옆 손가락을 살짝 움직이고 한쪽 눈썹을 올렸다 내려요.',
    caption: '음…?',
  },
  {
    id: 'celebrate',
    title: '축하해요!',
    emotion: '축하',
    posePrompt: '파티 모자를 쓰고 양팔을 높이 벌린 채 작은 축하 폭죽을 든 자세',
    actionPrompt: '폭죽을 든 손목을 가볍게 돌리고 입을 활짝 웃어요.',
    caption: '축하해!',
  },
  {
    id: 'goodnight',
    title: '좋은 꿈 꿔',
    emotion: '편안함',
    posePrompt: '달 모양 쿠션을 끌어안고 담요를 덮은 채 두 다리를 모아 앉은 자세',
    actionPrompt: '쿠션을 안은 손을 살짝 감싸고 눈꺼풀을 천천히 감아요.',
    caption: '잘 자',
  },
  {
    id: 'goodbye',
    title: '다음에 또 봐',
    emotion: '작별 인사',
    posePrompt: '한 손은 여행 가방을 잡고 다른 손은 높이 들어 뒤돌아 인사하는 자세',
    actionPrompt: '인사하는 팔과 손목만 두 번 흔들며 눈을 한 번 깜빡여요.',
    caption: '또 만나!',
  },
  {
    id: 'welcome',
    title: '어서 와요',
    emotion: '환영',
    posePrompt: '작은 문 옆에서 두 팔을 양옆으로 크게 벌려 손님을 맞는 자세',
    actionPrompt: '벌린 두 손을 안쪽으로 살짝 모으며 웃어요.',
    caption: '어서 와',
  },
  {
    id: 'proud',
    title: '멋진 나',
    emotion: '뿌듯함',
    posePrompt: '선글라스를 쓰고 한 손은 허리에, 다른 손은 안경테에 댄 멋진 자세',
    actionPrompt: '안경테를 잡은 손목을 살짝 움직여요.',
    caption: '나 좀 멋져',
  },
  {
    id: 'shy',
    title: '부끄러워요',
    emotion: '수줍음',
    posePrompt: '작은 꽃 한 송이를 등 뒤에 숨기고 한 손으로 붉어진 볼을 가린 자세',
    actionPrompt: '볼을 가린 손가락을 꼼지락거리고 눈을 수줍게 깜빡여요.',
    caption: '헤헤',
  },
  {
    id: 'rainy',
    title: '시무룩한 날',
    emotion: '아쉬움',
    posePrompt: '노란 우산을 들고 장화에 발을 모은 채 빗방울을 바라보는 자세',
    actionPrompt: '우산 손잡이를 쥔 손을 가볍게 고쳐 잡고 눈을 깜빡여요.',
    caption: '시무룩',
  },
  {
    id: 'sick',
    title: '오늘은 아파요',
    emotion: '아픔',
    posePrompt: '마스크와 이마의 냉찜질 팩을 하고 담요에 싸인 채 체온계를 든 자세',
    actionPrompt: '체온계를 든 손가락을 살짝 움직이고 눈꺼풀이 천천히 감겨요.',
    caption: '쉬어 갈게',
  },
  {
    id: 'exercise',
    title: '튼튼해질 거야',
    emotion: '의욕',
    posePrompt: '머리띠를 두르고 양손으로 작은 아령을 들어 올리는 운동 자세',
    actionPrompt: '두 팔꿈치를 번갈아 접어 아령을 조금 들어 올려요.',
    caption: '으쌰으쌰',
  },
  {
    id: 'birthday',
    title: '생일 축하해',
    emotion: '축하와 사랑',
    posePrompt: '생일 초 하나를 꽂은 작은 케이크를 양손에 조심스럽게 받쳐 든 자세',
    actionPrompt: '케이크를 받친 손을 조심스럽게 모으고 입을 작게 오므려요.',
    caption: '생일 축하해',
  },
  {
    id: 'promise',
    title: '꼭 약속해',
    emotion: '약속',
    posePrompt: '한 손을 앞으로 내밀어 약속을 청하고 다른 손을 가슴에 얹은 자세',
    actionPrompt: '앞으로 내민 손가락을 천천히 접었다 펴요.',
    caption: '약속!',
  },
] as const;
